# Site settings
title: BrainTrain
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#aa settings
#baseurl: "/dwarna/braintrain" # the subpath of your site, e.g. /blog/
#url: "http://users.abo.fi/dwarna" # the base hostname & protocol for your site

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

encoding: utf-8

# Build settings
markdown: kramdown

host: 0.0.0.0